# Generated by Django 5.0 on 2023-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('eid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('eemail', models.EmailField(max_length=254)),
                ('eaddress', models.TextField()),
            ],
        ),
    ]
